- .eslintrc.js
- .gitignore
- .prettierrc
- README.md
- controllers/app.controller.ts
- interface/cat.interface.ts
- main.ts
- modules/app.module.ts
- nest-cli.json
- package-lock.json
- package.json
- services/app.service.ts
- test/app.controller.spec.ts
- test/app.e2e-spec.ts
- test/jest-e2e.json
- tsconfig.build.json
- tsconfig.json
package.json 은 프런트와 통합해서 하나로 관리합니다.
eslint, prettier 는 nest 기본설정이니 담당분이 수정해주세요.
일단 이렇게 만들어보겠습니다.
> 백엔드 NestJS 구조 간단 설계

- .github/workflows/node.js.yml
이 PR보시면 우선적으로 승인해주세요.
테스트 관련 CI 환경 설정 입니다.
> 테스트: github CI/CD 에 e2e 테스트 추가

- .github/workflows/node.js.yml
> CI name 영어로 변경

- .github/workflows/node.js.yml
- components/example/Counter/eungi.js
> CI 테스트용 PR

- controllers/auth.controller.ts
- tsconfig.json
> 수정: 프런트엔드 설정으로 인한 백엔드 오류 수정

- components/SignUp/common/styles.js
- controllers/auth.controller.ts
- pages/signup.js
* text-decoration 에 number 를 사용하지 마세요.
* import 에 대한 경로가 정상인 지 확인해주세요.
> 수정: 프런트엔드 오류 해결

- controllers/auth.controller.ts
컨트롤러에서 반환하는 메시지에는 StatusCode 가 포함되기로 했었습니다.
프런트에서 사용할 예정입니다.
> 수정: 모든 응답에 statusCode 반영

- controllers/auth.controller.ts
앞으로 JSDoc 적극 반영하겠습니다.
선행해주신 @quavious 님 감사합니다.
이해 안되는 부분을 질문 할 수 있도록 author 명시해두는게 좋을 것 같습니다.
> feature: 인증 컨트롤러 JSDoc 업데이트

- components/SignUp/Auth/index.js
- components/landing/ContentBlock/LeftContentBlock/index.js
이메일 입력창의 맞춤법 검사 off 
* landing 페이지의 이메일 입력창
* signup 페이지의 이메일 입력창
> fix: email 입력창 맞춤법 검사 off

- .prettierrc
- components/SignUp/Auth/index.js
- components/SignUp/Auth/style.js
- components/SignUp/Info/index.js
- components/SignUp/Interest/index.js
- components/SignUp/ProgressBar/style.js
- components/SignUp/common/styles.js
- components/globalStyles/index.js
- components/landing/ContentBlock/LeftContentBlock/style.js
- components/landing/ContentBlock/index.js
- controllers/auth.controller.ts
- hooks/useInput.js
- next.config.js
- redux/actions/signup/auth.js
- redux/actions/signup/info.js
- redux/actions/signup/interest.js
- redux/reducers/signup/index.js
- redux/sagas/signup/signup.js
- redux/selectors/signup/index.js
* controllers/auth.controller.ts 83번째 줄 확인 바랍니다
> lint: prettier arrowParens 옵션 avoid -> always로 변경

- components/common/ScrollTop/index.js
- components/common/ScrollTop/style.js
- components/globalStyles/_Variables.js
- lib/scrollToTop.js
- lib/toScrollTop.js
- pages/index.js
> feature: ScrollTop 기능을 가진 컴포넌트를 작성하고 랜딩 페이지에 추가

- components/landing/ContentBlock/LeftContentBlock/index.js
- components/landing/Header/index.js
- redux/actions/common/user.js
- redux/reducers/common/user.js
- redux/reducers/index.js
- redux/selectors/common/user.js
* 로그인한 유저에 대한 액션, 리듀서, 셀렉터 작성
* 기존 컴포넌트 내부에서 사용하던 임시 loggedIn 상태를 store 내 me의 여부로 대체
> feature: 로그인한 유저에 대한 액션, 리듀서, 셀렉터 작성

- controllers/auth.controller.ts
- modules/mail.module.ts
- services/email.service.ts
* 이메일 전송 실패했는데 성공 메시지와 함께 file ENOENT 에러가 콘솔에 발생하는 것을 해결하였습니다.
* * *
> 수정: 회원가입 이메일 인증 오류 해결 

- components/SignUp/Auth/index.js
- components/landing/ContentBlock/LeftContentBlock/index.js
- components/landing/Header/index.js
- pages/signup.js
- redux/reducers/index.js
- redux/sagas/index.js
- redux/sagas/signup/auth.js
- redux/sagas/signup/index.js
- redux/sagas/signup/info.js
- redux/sagas/signup/interest.js
- redux/sagas/signup/signup.js
* 콘솔에 컨벤션 관련 워닝이 지속적으로 나오는 문제 수정
* 주소창에 표시되는 페이지명이 로우케이스가 아닌 카멜케이스인 문제 수정
> fix: 해결 못한 네이밍 컨벤션 문제 수정

- controllers/auth.controller.ts
- lib/backend/log.ts
- models/entities/user.verify.ts
- models/repositories/user.repository.ts
- services/email.service.ts
- services/email/user-verify.pug
- services/user.service.ts
1. 인증 기간이 만료되면 삭제되지 않았던 부분 수정 ( 기존 요청에 대해 만료 시 삭제 )
2. 인증 기간 만료 시 삭제 후 재생성 및 반환 코드 작성
3. 동일한 email request 에서 새로운 레코드가 생성되던 문제 해결
4. 구조분해할당으로 코드 가독성 향상
1. 이메일 검증 Api 가 작성되었습니다.
2. /api/user/verify-email 이며 내용 형식은 email 로 첨부 전송되는 url 과 동일합니다.
> 기능: 이메일 검증 Api 작성 및 기존 코드 리팩터링

- controllers/auth.controller.ts
- models/repositories/user.repository.ts
- models/repositories/user.verify.repository.ts
- services/auth.service.ts
- services/email.service.ts
- services/user.service.ts
* * *
* validation 서비스 추가
* controller 가독성 향상
* * *
* 백엔드 위험 코드 수정 (@bear-bear-bear )
* 가독성 향상
> fix: 백엔드 코드 리팩터링 및 코드 어시스트 수정

- next/.env
- next/.gitignore
- next/lib/apiClient.js
- next/next.config.js
- next/package-lock.json
- next/package.json
- next/redux/sagas/common/user.js
- next/redux/sagas/index.js
- next/redux/sagas/signup/index.js
.env가 PR로 올라온 점에 놀라실 수 있는데, next에선 .env.local 에 비밀 값들이 들어있고 .env는 공개 변수에 사용한다고 합니다. ([#1](https://github.com/vercel/next.js/tree/canary/examples/environment-variables)) ([#2](https://nextjs.org/docs/basic-features/environment-variables))
> feat: next env 설정, axios대신 apiClient 적용

- nest/main.ts
> feature: cors 허용 옵션 작성

- nest/modules/mail.module.ts
* secure 을 무조건 true 로 설정해서 성공한 사례가 있으니 한번 이렇게 시도해보죠.
> fix: secure 무조건 true 설정

- nest/controllers/auth.controller.ts
> fix: 이메일 검증 api 항상 false 리턴하는 오류 수정

- next/.eslintrc.js
* no-shadow 관련 옵션 off > warn
[#91](https://github.com/bear-bear-bear/mogakco/issues/91)
> style: eslint 규칙 수정

- nest/models/entities/user-field.entity.ts
- nest/models/entities/user-verify.entity.ts
- nest/models/entities/user.entity.ts
* field 테이블 작성
* user 와 field 연관 관계 작성
> feature: field 항목 데이터 모델링

- nest/controllers/auth.controller.ts
- nest/controllers/user.controller.ts
- nest/modules/user.module.ts
- nest/services/auth.service.ts
- nest/services/email/user-verify.pug
- nest/services/passport/jwt.refresh.strategy.ts
- nest/services/user.service.ts
* 기존 회원가입 api 가 /api/user 로 시작했었던 부분을 /api/auth 로 변경하였습니다. ( 사용자 컨트롤러가 작성되면서 네이밍 충돌 )
* postman API 모두 수정해두었습니다.
> feature: 목적 구분을 위한 컨트롤러 분리

- nest/controllers/user.controller.ts
- nest/modules/user.module.ts
- nest/services/user.service.ts
- nest/test/unit/user/index.test.ts
> 기능: 희망 분야 목록 불러오기 Api 작성

- nest/controllers/user.controller.ts
- nest/models/entities/users-job.entity.ts
- nest/services/user.service.ts
* skills 와 동일하게 설계 되었습니다.
* GET /api/user/jobs
* skills 와 같이 중복 방지는 CREATE 요청 Api 에서 처리할 예정입니다.
* * *
> 백엔드: 직업 모델링과 리스트 불러오기 Api

- next/lib/APIs.js
- next/redux/reducers/signup/index.js
- next/redux/sagas/common/user.js
- next/redux/sagas/signup/index.js
* API를 next/libs/APIs.js 에서 관리
* 각 API에 대한 주석 추가
* skills와 job API 주석처리 해제
> fix: 서버 측 API 변경에 따라 API url 변경 및 적용

- nest/.eslintrc.json
- nest/models/entities/helper/abstract.ts
- nest/models/entities/user-field.entity.ts
- nest/models/entities/user-verify.entity.ts
- nest/models/entities/user.entity.ts
- nest/models/entities/users-job.entity.ts
> 기능: 백엔드 리팩터링 및 모델링 수정

- nest/services/auth.service.ts
* Web 이 아닌 임의의 웹 도구 ( Postman ,... ) 를 사용하여 회원가입 요청 시, 이메일 검증을 수행하지 않아도 pass 되는 문제를 수정했습니다.
> 사용자 회원가입에 인증 검증 로직 추가

- .github/workflows/node.js.yml
- nest/.env.example
- nest/controllers/auth.controller.ts
- nest/factory/users-field.factory.ts
- nest/factory/users-job.factory.ts
- nest/package-lock.json
- nest/package.json
- nest/seeders/user-props.ts
- nest/test/e2e/auth/email-verification.e2e-spec.ts
- nest/test/e2e/user/user-props.e2e-spec.ts
- nest/test/type/mock-data-type.ts
- 직업 리스트 불러오기 Api 테스트 작성
- 분야 리스트 불러오기 Api 테스트 작성
- 이메일 인증 URL Api 발송 테스트 작성
- 이메일 URL 클릭 시 검증 Api 테스트 작성
- 클라이언트에서 이메일 인증 여부 검사 (true | false) Api 테스트 작성
- 테스트 도중 발견한 버그 수정
- 테스트 도중 리팩터링 수행
- 시딩 환경 구성
- 희망 분야, 직업 목록 시딩 구현
> 백엔드 분야, 직업 목록, 이메일 Api 테스트, 시딩 환경 작성

- next/components/common/Input/EmailInput/index.tsx
- next/components/signup/Start/index.tsx
- next/components/signup/Start/useEffectSignUpStart.tsx
- next/hooks/useInput.tsx
- next/lib/APIs.ts
- next/lib/apiClient.ts
- next/redux/reducers/signup/index.ts
- next/redux/sagas/signup/index.ts
- next/typings/auth.ts
- next/typings/common.ts
* 새벽시간 대, 질문주신 내용 참고할 수 있도록 개선안 PR 입니다.
* slicer, 사가, 기존 any 였던 SagaError 부분에 타입을 작업하였고, start 페이지 일부 리팩터링 수행하였습니다.
* 변경된 파일내용이 100% 수정된 것은 아닙니다.
* reducer 는 데이터를 무조건 payload 값으로 받습니다. 사가에서 지켜지고 있지 않습니다.
* * *
* **전반적인 코드 리뷰는 회의에서 진행하겠습니다.** ( 코멘트는 참고만 )
> REFACTOR: signup redux, start page 타입스크립트 작업 및 리팩터링

- next/redux/reducers/common/user.ts
- next/redux/reducers/landing/index.ts
- next/redux/reducers/signup/index.ts
- next/redux/sagas/common/user.ts
- next/redux/sagas/signup/index.ts
- next/redux/selectors/common/user.ts
- next/redux/selectors/signup/index.ts
- next/typings/auth.ts
- next/typings/common.ts
> REFACTOR: redux/ 타입 정상화

- next/components/common/AuthContainer/index.tsx
- next/components/common/Button/index.tsx
- next/components/common/Button/style.tsx
- next/components/common/CustomHead/index.tsx
- next/components/common/Form/index.tsx
- next/components/common/InputWrapper/index.tsx
- next/components/common/ScrollTop/index.tsx
- next/components/common/Select/index.tsx
- next/components/common/Warning/index.tsx
- next/lib/APIs.ts
- next/lib/fromActionTypes.ts
- next/redux/reducers/signup/index.ts
- next/redux/sagas/signup/index.ts
- next/tsconfig.json
- next/typings/auth.ts
* 제가 수정하지 못하는 부분이 존재합니다. TODO 남겼읍니다.
* * *
> REFACTOR: 프런트엔드 타입 분할 작업 1차 [galaxy4276]

- next/components/globalStyles/_FontFace.tsx
- next/components/globalStyles/index.tsx
- next/components/globalStyles/media.tsx
- next/components/landing/Container/index.tsx
- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
- next/components/landing/ContentBlock/LeftContentBlock/style.tsx
- next/components/landing/ContentBlock/RightContentBlock/index.tsx
- next/components/landing/ContentBlock/index.tsx
- next/components/landing/Header/index.tsx
- next/components/landing/Header/style.tsx
- next/components/landing/MiddleBlock/index.tsx
- next/components/signup/End/index.tsx
- next/custom.d.ts
- next/pages/index.tsx
- next/tsconfig.json
> refactor: 타입스크립트 정상화 작업 components/ 1차

- next/components/common/Button/index.tsx
- next/components/common/Button/style.tsx
- next/components/common/Desc/index.tsx
- next/components/common/Desc/style.tsx
- next/components/common/Input/EmailInput/index.tsx
- next/components/common/Input/PasswordInput/index.tsx
- next/components/common/Input/TextInput/index.tsx
- next/components/common/Input/TextInput/style.tsx
- next/components/common/Label/index.tsx
- next/components/common/Label/style.tsx
- next/components/signup/RequiredInfo/index.tsx
- next/components/signup/Start/index.tsx
- next/stories/Button.stories.tsx
- next/stories/Button.tsx
- next/stories/Header.tsx
`size -> scale`
input element 관련 'size' prop만 수정하면 해결이였지만, 코드 일관성을 위해 다른 컴포넌트의 크기 관련 옵션 이름도 수정했습니다.
> FIX: 기존 html에 있는 size prop를 커스텀 prop name으로 사용하여 생기던 문제 수정 - close #172 [bear-bear-bear]

- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
- next/components/signup/End/index.tsx
- next/components/signup/Start/index.tsx
[useeffect-vs-uselayouteffect](https://daveceddia.com/useeffect-vs-uselayouteffect/)
UX 향상을 위해 포커스 이벤트를 useLayoutEffect로 변경했습니다
> refactor: 페이지 진입 시 주던 focus효과를 useEffect -> useLayoutEffect로 변경

- nest/controllers/auth.controller.ts
- nest/package-lock.json
- nest/package.json
* accessExpiredAt 필드가 UTC 기준으로 반환됩니다.
> FEATURE: 로그인 성공 시 만료 기한 필드 추가

- nest/controllers/user.controller.ts
- nest/models/entities/helper/abstract.ts
- nest/models/entities/room-user.entity.ts
- nest/models/entities/room.entity.ts
- nest/models/entities/user.entity.ts
- nest/models/repositories/user.repository.ts
- nest/test/e2e/user/mypage.e2e-spec.ts
- nest/typing/auth.ts
* 두 개의 PR 이 하나에 병합되어 작업되었습니다. ( 사유: 코드 리뷰 팀원 늦잠 )
* [ERDCloud](https://www.erdcloud.com/d/5C3evcdRWn85gfjc2) 설계된 방안 토대로 TypeORM 에서 작성
* 초기 작성이라 문제 여지도 있습니다. 개발 중 수정 예정
* * *
* * *
* 사용자 본인 확인 Api 가 완성되었습니다.
* e2e 테스트 작성도 포함하였습니다.
> FEATURE: 채팅 관련 ORM 모델링 작성 & 사용자 본인 확인 Api 작성

- next/components/common/Button/index.tsx
- next/components/common/Button/style.tsx
- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
- next/components/landing/ContentBlock/LeftContentBlock/style.tsx
- next/components/signup/End/index.tsx
- next/components/signup/OptionalInfo/index.tsx
- next/components/signup/RequiredInfo/index.tsx
- next/components/signup/Start/index.tsx
- next/hooks/useIsomorphicLayoutEffect.tsx
* [useLayoutEffect * SSR 관련](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a) 이슈 해결
* 랜딩페이지 isFirstBlock 타입 에러 해결
* 사용하지 않는 모듈 제거 (eslint warning)
* [emotion Transient props 이슈](https://mygumi.tistory.com/382) 해결
> FIX: 프런트 자잘한 이슈 해결

- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
- next/components/landing/ContentBlock/RightContentBlock/index.tsx
- next/components/landing/Footer/index.tsx
- next/components/landing/Header/index.tsx
- next/components/landing/MiddleBlock/index.tsx
- next/package-lock.json
- next/package.json
- next/pages/_app.tsx
- next/pages/index.tsx
antd 라이브러리의 grid를 chakra 라이브러리의 Flex 컴포넌트로 대체했습니다
> REFACTOR: antd 제거 - close #166

- nest/controllers/chat.gateway.ts
- next/components/video-chat/ChatSection/Chat/style.tsx
- next/components/video-chat/ChatSection/ChatList/index.tsx
- next/package-lock.json
- next/package.json
- next/pages/chat/[id].tsx
> FEATURE: 채팅방 연결, 일부 이슈 픽스, SWR 설치

- next/hooks/useSignUp.tsx
- next/pages/signup.tsx
* 기존 pages/signup 에서 관리하던 상태들은 다른 페이지에서도 접근 및 수정을 필요로 합니다.
* 관련 State 와 Modifier 를 묶은 hooks 를 공유하여 사용합니다.
> REFACTOR: SWR Hooks 관리

- next/pages/signup.tsx
> FIX: initial error 수정

- next/hooks/useSignUp.tsx
> feature: 유저 상태값 추가

- nest/controllers/chat.gateway.ts
- next/components/video-chat/ChatSection/Chat/Announcement.tsx
- next/components/video-chat/ChatSection/Chat/style.tsx
- next/components/video-chat/ChatSection/InputBox/index.tsx
- next/components/video-chat/ChatSection/InputBox/style.tsx
- next/hooks/useInput.tsx
- next/package-lock.json
- next/package.json
- next/pages/chat/[id].tsx
* 한 채널 연결에서 모든 유저들이 접속함을 공유할 수 있는 시스템 구축 ( 콘솔에서 확인 가능 )
* 프런트 채팅 enter 시 채팅 보내지고, alt + enter 시 줄바꿈 되게 수정 ( 채팅자체가 보내지지는 않음 )
* 채팅 입력 박스가 이제 alt+enter 시 자동으로 늘어납니다. ( 자동으로 줄어도 듭니다. mnbg )
* https://www.npmjs.com/package/react-textarea-autosize
> FEATURE: 소켓 커넥션 작성, 프런트엔드 수정

- nest/controllers/auth.controller.ts
> MODIFY: request url changes

- next/components/sign-up/Required/Sections/ErrorSection.tsx
- next/components/sign-up/Required/Sections/PasswordSection.tsx
- next/components/sign-up/Required/Sections/TermSection.tsx
- next/components/sign-up/Required/Sections/UsernameSection.tsx
- next/components/sign-up/Required/index.tsx
- next/components/sign-up/Required/typings.ts
기존 state로 관리하던 에러 관리 로직을 전부 react-hook-form 에서 제공하는 기능으로 옮겨 리렌더링을 최소화 시켰습니다. 기존과 작동은 동일합니다.
> FIX: 기존 오지는 리렌더링이 일어나던 Required 페이지의 성능 대폭 개선

- nest/controllers/auth.controller.ts
- nest/main.ts
- next/components/sign-in/index.tsx
- next/lib/apiClient.ts
- next/lib/fetchers.ts
- next/pages/index.tsx
- next/typings/auth.ts
* 로그인을 연장처리할 지 검증하고 처리하는 인터셉트를 작성하였습니다.
* 로그인 관련 Api 를 작성하였습니다.
* 백엔드 CORS 오류를 수정하였습니다.
* 백엔드 Api 오류를 수정하였습니다
> FEATURE: 로그인 처리

- next/pages/index.tsx
> MODIFY: 로그인 연장 테스트 개선

- next/pages/index.tsx
> FEAT: 로그인 연장에 숟가락 얹기

- next/components/landing/Header/index.tsx
- next/pages/dashboard/index.tsx
*  Link 아래 a 가 아닌 다른 엘리먼트가 온 문제 수정
* passHref 관련 문제 수정
> fix: next/Link 관련 심각한 seo 이슈 해결

- next/lib/apiClient.ts
작성해주신 axios 인터셉터 에서 아래 로직이 3번 반복되고 있어 함수로 빼보았습니다.
``` js
const {
data: { accessToken, expirationTime },
} = await refreshAccessTokenApi();
localStorage.setItem('expirationDate', expirationTime);
memoryStore.set(Memory.ACCESS_TOKEN, accessToken);
```
#225 와 같은 파일 수정으로 충돌 우려 있습니다.
> REFACTOR: 반복되는 access 재발급 요청 로직 함수화

- next/components/dashboard/Container/style.tsx
- next/components/globalStyles/media.tsx
> STYLE: media screenSizes 객체 이름을 breakpoints 로 변경하기

- next/components/sign-up/Required/Sections/PasswordSection.tsx
- next/components/sign-up/Required/index.tsx
- next/components/sign-up/Start/index.tsx
#234 에 언급된 문제에 더해 에러가 있어도 다음 단계로 넘어가지는 문제도 해결
> FIX: #234 해결

- nest/services/auth.service.ts
- next/components/landing/Header/AuthButtons.tsx
- next/components/sign-up/Optional/index.tsx
- next/lib/apiClient.ts
- next/lib/fetchers.ts
- next/pages/_app.tsx
* 프런트엔드 회원가입 시 로그인과 완전 동일하게 처리되게 끔 수정하였습니다. ( 누락 사항 1건 수정 )
* 다른 탭에서 로그아웃을 감지하는 로직을 더 쉽게 바꿔서 ( api 를 동작안해도 되게 끔 ) 리렌더링 문제를 해결하였습니다.
테스트 강도를 높이지 않을거면 좀 더 꼼꼼하게 검수하고 작성, 테스트를 해봐야겠네요.
테스트를 만드는 비용이 항상 싸다는 것에 불구하고 잘 작성안하게 되는 것 같습니다.
반성하겠습니다.
( 반성의 의미로 저녘은 배달 음식 먹겠음 )
Closes #232
> FIX: 프런트엔드 회원가입 로그인 패스 문제, useEffect storage event 이슈 해결

- nest/controllers/auth.controller.ts
- nest/services/auth.service.ts
> FEATURE: sign-out 도 user 추가 및 login, join 에 해시값 삭제

- nest/controllers/auth.controller.ts
- nest/test/e2e/auth/user-login.e2e-spec.ts
- next/hooks/useUser.tsx
- next/lib/fetcher.ts
- next/pages/video-chat/[id].tsx
- next/typings/auth.ts
#253 에서 요청받은 내용 중
* 불필요한 주석 제거
* 타입 에러 수정
을 해결하였고, 백엔드 응답이 기존 기획과 다른 점을 발견하여 #253 코멘트에 언급하였습니다.
> fix: useUser 타입 에러 수정, 서버측 user 정보 요청 응답 flat하게 변경

- nest/test/e2e/auth/email-verification.e2e-spec.ts
- nest/test/e2e/auth/user-join.e2e-spec.ts
- nest/test/e2e/auth/user-login.e2e-spec.ts
- nest/test/e2e/helper/module.ts
- nest/test/e2e/user/mypage.e2e-spec.ts
- nest/test/e2e/user/user-props.e2e-spec.ts
* 각 e2e 마다 Nest Test Library 를 사용하여 Test Application 을 실행하는 부분을 추상화 하였습니다.
> FEATURE: 테스트 애플리케이션 반환 함수 작성 및 e2e 반영

- nest/main.ts
- nest/package-lock.json
- nest/package.json
- nest/src/authentication/auth.controller.ts
- nest/src/authentication/auth.service.ts
- nest/src/authentication/dto/create-user.dto.ts
- nest/src/authentication/dto/login-user.dto.ts
- nest/src/common/decorators/swagger/auth.decorator.ts
- nest/src/common/helpers/app.helper.ts
- nest/src/common/helpers/enum.helper.ts
- nest/src/models/user/entities/user-field.entity.ts
- nest/test/e2e/auth/email-verification.e2e-spec.ts
- nest/test/e2e/auth/user-join.e2e-spec.ts
* Swagger 생성 코드를 작성하고 모듈화 하였습니다.
* App 관련 Log 함수를 작성하고 모듈화 하였습니다.
* 인증에 관련된 Swagger 데코레이터들을 격리하고 한 데코레이터로 통합하였습니다.
* 인증 컨트롤러에 Swagger 문서를 적용하였습니다.
* CI 오류 정상입니다.
* * *
* 서버 애플리케이션을 실행하고 해당 도메인으로 접속하면 문서를 이용할 수 있습니다.
예 ) localhost:8080/
> TEST: Swagger 환경 설정 및 인증 관련 Swagger Document 작성

- nest/.env.example
- nest/src/common/helpers/test.helper.ts
* 변경된 구조 경로 재설정
* 테스트 헬퍼 함수 개선
> fix: 데이터베이스 시더 에러 수정 - 우선순위 1

- nest/src/common/helpers/app.helper.ts
> feat: swagger 인증 수단에 refreshToken 추가

- next/next.config.js
- next/package-lock.json
- next/package.json
* Webpack 5 -> Webpack 4 
* Framer-Motion 설치
> fix: 프런트엔드 오류 수정

- nest/src/authentication/auth.controller.ts
- nest/src/common/decorators/swagger/auth.decorator.ts
> fix: 누락된 401 정보 입력 & Swagger 누락사항 작성

- next/lib/apiClient.ts
> fix: httponly 설정에 따라 기존 document.cookie 사용 로직 주석처리, risk 주시할것

- .github/workflows/node.js.yml
- nest/test/e2e/auth/user-login.e2e-spec.ts
- next/package.json
> ci: 프런트엔드 패키지 인스톨 속도 향상

- nest/src/authentication/auth.controller.ts
- nest/test/e2e/auth/user-login.e2e-spec.ts
> fix: /api/auth/user statusCode 이슈 수정

- nest/main.ts
- nest/src/authentication/auth.controller.ts
- nest/src/authentication/auth.module.ts
- nest/src/authentication/auth.service.ts
- nest/src/authentication/strategies/jwt.refresh.strategy.ts
- nest/src/authentication/strategies/jwt.strategy.ts
- nest/src/common/exceptions/http-exception.filter.ts
- nest/src/common/guards/jwt-guard.ts
- nest/src/common/guards/jwt-refresh.guard.ts
* 인증 프레임워크, Nest 에서 오류를 처리해주지 않는 부분 수동으로 처리
* 인증에 관한 에러를 수동 처리와 함께 Guard 기능을 확장하여 제대로 잡아주게 끔 변경
* 인증 부분 대체적인 서비스 코드 안정성, 가독성, 효율 향상 
Closes #289
> fix: 인증 기능 오류 수정 및 리팩터링 

- next/hooks/useUser.tsx
- next/lib/apiClient.ts
- next/lib/token.ts
Authorization이 필요한 페이지인데, 리프레쉬 토큰이 쿠키에 없는데 액세스 토큰은 메모리에 있는 상황이라면 (사용자가 쿠키를 고의로 지웠을 경우) 리디렉션 되도록 설정했습니다.
@lib/token 관련 리팩터링
> feat: useUser 보완

- nest/src/common/decorators/swagger/chat.decorator.ts
- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.module.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/entities/chat.entity.ts
- nest/src/models/user/entities/user.entity.ts
- nest/src/models/user/repositories/chat.repository.ts
- next/components/video-chat/ChatSection/ChatList/index.tsx
- next/hooks/useSocket.tsx
- next/hooks/useUser.tsx
- next/package-lock.json
- next/package.json
* 방 입장, 퇴장, 유저 수, 채팅에 대한 소켓 이벤트와 서비스 프로바이더를 구현하였습니다.
* useUser 타입 정보를 수정하였습니다.
* 채팅 모델링을 작성하였습니다.
* 프런트엔드에 테스트용 이벤트 리스너를 작성하였습니다.
* useSocket 을 보완하였습니다.
> feat: 소켓 서버, 채팅에 대한 기능 추가

- nest/src/authentication/auth.controller.ts
* 요청 API 수정하였습니다.
```
{
"statusCode": 200,
"message": "로그인에 성공하였습니다!",
"user": {
"id": 1,
"createdAt": "2021-09-08T09:07:22.004Z",
"updatedAt": "2021-09-10T08:13:52.000Z",
"deletedAt": null,
"username": "mogauser",
"email": "mogakco35@gmail.com",
"skills": [
{
"id": 2,
"name": "안드로이드"
},
{
"id": 7,
"name": "게임 서버"
},
{
"id": 9,
"name": "풀스택"
},
{
"id": 10,
"name": "IOS"
},
{
"id": 11,
"name": "임베디드"
}
],
"job": {
"id": 1,
"createdAt": "2021-09-08T09:07:21.515Z",
"updatedAt": "2021-09-08T09:07:21.515Z",
"name": "보안 솔루션 개발자"
}
},
"expiration": "2021-09-10T08:24:39.122Z",
"accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtb2dhdXNlciIsImlhdCI6MTYzMTI2MTY3OCwiZXhwIjoxNjMxMjYyMjc4fQ.FFNLP1AbcnJtczCN8qe03qosFisuhOhSR32mcY_sVa8"
}
```
> feat: API 요청 수정

- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/user/repositories/chat.repository.ts
- next/components/video-chat/ChatSection/Chat/Announcement.tsx
- next/components/video-chat/ChatSection/Chat/MyTextChat.tsx
- next/components/video-chat/ChatSection/Chat/index.tsx
- next/components/video-chat/ChatSection/Chat/style.tsx
- next/components/video-chat/ChatSection/ChatList/index.tsx
- next/components/video-chat/ChatSection/InputBox/index.tsx
> feat: 채팅 구현

- next/components/common/Profile/ProfileModal.tsx
- next/components/common/Profile/index.tsx
- next/components/common/Profile/style.tsx
- next/components/common/ServiceHeader/index.tsx
- next/components/common/ServiceHeader/style.tsx
- next/components/globalStyles/_Resets.tsx
- next/components/my-page/Header/index.tsx
- next/components/my-page/Header/style.tsx
- next/pages/my-page/account-setting.tsx
- next/pages/my-page/calendar.tsx
- next/pages/my-page/index.tsx
이 PR에서 my-page 페이지에 추가되어 있고, 병합시 바로 올라갈 PR에서 dashboard 페이지에도 적용할 예정입니다.
> feat: 여러 서비스 페이지에서 쓰일 프로필 컴포넌트 추가

- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/interface/gateway.ts
- next/components/video-chat/ChatSection/Chat/Announcement.tsx
- next/components/video-chat/ChatSection/Chat/index.tsx
- next/components/video-chat/ChatSection/ChatList/index.tsx
- next/typings/chat.ts
> feat: 입 퇴장 프런트 백엔드 구현

- next/components/globalStyles/index.tsx
- next/next.config.js
- next/package-lock.json
[Next.js - 11](https://nextjs.org/blog/next-11#nextjs-live-preview-release)
#270 에서 모든 패키지를 최신버전으로 이미 업데이트 하여, 특별한 변경사항은 없네요 ㅋ ㅋ..
> feat: nextjs migration

- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/repositories/room-user.repository.ts
- nest/src/models/user/user.controller.ts
- nest/src/models/user/user.service.ts
- nest/test/e2e/user/user-props.e2e-spec.ts
- next/src/components/video-chat/ChatSection/ChatList/index.tsx
- next/src/components/video-chat/ChatSection/Container/index.tsx
- next/src/components/video-chat/ChatSection/Container/style.tsx
- next/src/components/video-chat/ChatSection/InputBox/index.tsx
- next/src/components/video-chat/ChatSection/index.tsx
- next/src/hooks/useSocket.tsx
- next/src/pages/video-chat/[id].tsx
- next/typings/chat.ts
* 기존 채팅 Pool 에 관한 이슈를 드디어 처리 하였습니다. ( #233 )
* 이제 Socket 연결은 1회 실행되며, 채팅 중 닉네임 변경, 재 입퇴장 및 문제를 해결하였습니다.
* 채팅방 입장 시 모든 유저는 익명 처리 됩니다.
* 채팅방 멤버 수 표기 기능을 구현하였습니다. 모든 유저의 입장 / 퇴장 이벤트 발생 시 멤버 수를 다시 계산하여 화면에 렌더링합니다.
Closes #233
> feat: 익명 채팅 및 멤버 수 표기 기능 작성

- nest/src/common/decorators/swagger/chat.decorator.ts
- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/interface/controller.ts
- nest/src/models/chat/interface/gateway.ts
- nest/src/models/chat/interface/service.ts
- next/src/components/video-chat/ChatSection/ChatList/index.tsx
- next/src/components/video-chat/ChatSection/Container/index.tsx
- next/src/components/video-chat/ChatSection/InputBox/index.tsx
- next/src/components/video-chat/ChatSection/index.tsx
- next/src/hooks/useSocket.tsx
- next/src/pages/video-chat/[id].tsx
* 백엔드는 주요 서버 구현부의 가독성을 향상시켰습니다.
* 프런트엔드는 프롭 드릴링 부분을 해결하였습니다.
> refactor: 백엔드/프런트엔드 소켓 서비스 부분 리팩터링

- nest/.env.example
- nest/main.ts
- nest/src/common/helpers/enum.helper.ts
- nest/src/config/app/config.module.ts
- nest/src/mail/assets/user-verify.pug
- nest/src/mail/email.service.ts
- nest/src/mail/mail.module.ts
- next/.env
- next/package-lock.json
- next/package.json
- next/src/components/video-chat/ChatSection/Chat/Announcement.tsx
- next/src/components/video-chat/ChatSection/Chat/index.tsx
- next/src/hooks/useSocket.tsx
- next/src/lib/apiClient.ts
- next/src/lib/enviroment.ts
* 프런트, 백엔드 모두 test, production, development 에 따라 환경설정이 달라집니다.
* 디렉터리 이동하면서 발생하던 경로 오류를 수정하였습니다.
* next 에 pm2 를 설치해두었습니다.
* 이메일 발송이 무조건 localhost 로 가는 오류를 해결하였습니다.
> feat: 개발 환경에 대해 분기 처리 및 테스트 및 프로덕션 로직 오류 수정

- nest/src/common/decorators/swagger/chat.decorator.ts
- nest/src/database/seeders/user-props.ts
- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/entities/room.entity.ts
- nest/src/models/chat/interface/controller.ts
- nest/src/models/chat/interface/service.ts
- nest/src/models/chat/repositories/room.repository.ts
- nest/src/models/user/user.service.ts
* 채팅방 진입용 Api 를 작성했습니다.
* 해당 Api 에 대한 Swagger 가 마련되어 있으며, 당장 작업이 필요하니 모든 Respnose Case 에 Example Scheme 를 작성해두었습니다.
* 백엔드 기능 빠르게 나오는 것이 급하다보니, 거의 로직짜는 시간만큼 맞먹는 테스트 작성이 제외되어 있습니다. 백엔드의 능력부족 죄송하며 테스트는 로직이 모두 완성된 후 작성하겠습니다.
* 테스트 없는 기능 작성 또한 말이 안되는 부분임을 인지하고 있습니다. ( 시간 부족에 대한 사유가 적절치 못함 )
* 작성할 수 있었을 지 모르나, 프로젝트 마감 기한이 1달 안남은 것에 대한 압박이 강합니다
> feat: 백엔드 채팅방 자동 찾기 및 생성 Api 구현

- nest/.env.example
- nest/src/authentication/auth.controller.ts
- nest/src/authentication/auth.service.ts
- nest/src/common/decorators/swagger/user.decorator.ts
- nest/src/config/app/config.module.ts
- nest/src/mail/email.service.ts
- nest/src/models/user/interface/controller.ts
- nest/src/models/user/repositories/user.repository.ts
- nest/src/models/user/user.controller.ts
- nest/src/models/user/user.service.ts
* 기존에 잘못 지웠던 Api 다시 열었습니다. 열면서 코드 수정하고 response 값 수정하였습니다. Swagger 작성 포함
* 배포환경에서 잘못되었던 코드들 수정하였습니다.
* 유저 컨트롤러에 타입정보를 부여하였습니다.
> fix: 프로덕션 잔버그 수정 및 유저 부속 정보 Api 개선 및 오픈

- nest/src/config/database/mariadb.module.ts
- nest/src/models/chat/entities/roles.entity.ts
- nest/src/models/chat/entities/user-roles.entity.ts
- nest/src/models/chat/repositories/roles.repository.ts
- nest/src/models/chat/repositories/user-roles.repository.ts
> feat: 사용자 역할 관련 모델링 작성 및 서버 반영

- next/src/components/dashboard/CardLink/Card.tsx
- next/src/lib/apis.ts
- next/src/pages/dashboard/index.tsx
- next/typings/auth.ts
* 프런트에서 수동으로 리다이렉션 되게 변경, api 에서는 roomId 응답
* 현재 에러 처리 모호함
> feat: 방 찾기 또는 생성 api 프런트엔드 연동

- nest/src/database/seeders/user-props.ts
- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/entities/room.entity.ts
- nest/src/models/chat/interface/service.ts
- nest/src/models/chat/repositories/room.repository.ts
- nest/src/models/user/entities/user.entity.ts
- - -
* 모든 방은 인원 수가 0 일 때, softDelete 되며 다시 재생성되는 디비 데이터 목록을 확인하였습니다.
* 방 랜덤 찾기 기능에 있던 문제를 수정하였습니다.
* 편리한 로컬 테스트를 위해 시드에서 mogauser2 를 생성합니다.
> feat: 채팅방 인원 수에 따른 자동 제거 구현

- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/interface/gateway.ts
- nest/src/models/chat/interface/service.ts
- nest/src/models/chat/repositories/anonymous-room-user.repository.ts
- next/src/components/video-chat/ChatSection/Chat/index.tsx
- next/src/pages/video-chat/[id].tsx
- next/typings/chat.ts
* 다중 탭 유저는 이제 서비스 개념에서 한 유저로 취급됩니다
* 저는 한 기능을 개발하고 다음 PR 로 리팩터링을 올리는 편입니다. 즉 다음 PR 에서 리팩터링
* 시골에서 리팩터링까지 생각하려니까 각이 안나옵니다.
> feat: 서비스 채팅 다중 유저 방지 기능 작성

- next/src/components/common/Button/style.tsx
- next/src/components/dashboard/Card/CardAnchor.tsx
- next/src/components/dashboard/Card/CardButton.tsx
- next/src/components/dashboard/Card/index.tsx
- next/src/components/dashboard/Card/style.tsx
- next/src/components/dashboard/Container/index.tsx
- next/src/components/video-chat/Container/style.tsx
- next/src/components/video-chat/Loading/index.tsx
- next/src/components/video-chat/Loading/style.tsx
- next/src/lib/apis.ts
- next/src/pages/dashboard/index.tsx
- next/typings/auth.ts
* 대쉬보드, 채팅방 컴포넌트 fade in, out 작업
* 시간이 2초 가량 지연될 시 로딩 element 적용
<br>
<br>
> feat: 채팅방 입장 전 UX 작업 - close #337

- next/src/components/video-chat/ChatSection/ChatList/index.tsx
- next/src/components/video-chat/ChatSection/ChatList/style.tsx
> feat: 새로운 채팅 추가 시 스크롤 방식 변경

- next/src/components/video-chat/ChatSection/InputBox/TuiEditor.tsx
- next/src/components/video-chat/ChatSection/InputBox/TuiEditorWrapper.tsx
- next/src/lib/apis.ts
- next/src/pages/api/chat/upload/index.ts
- next/typings/chat.ts
'파일 업로드 중입니다..' 같은 안내 구문에 대해선 추후 여유가 있을때 추가하겠습니다.
**multipart/formdata 형식**으로 이미지 **한개씩**만 전송합니다
> feat: 이미지 업로드 프런트측 기능 작성 (mock api 사용)

- next/src/components/common/SVGButton/index.tsx
- next/src/components/common/SVGButton/style.tsx
포스기에서 한 작업이라 누락사항을 잡지 못했습니다 쏘링
> !HOTFIX: 누락된 스타일 파일 추가

- next/src/components/video-chat/ChatSection/ChatList/index.tsx
> fix: 채팅장 스크롤 bottom 잘 안되던 문제 해결

- next/src/components/video-chat/ChatSection/Chat/Message.tsx
* 이제 중복 링크에 대해 제대로 한 가지 card만 띄웁니다.
* 이제 사용자가 `'www' | 'http' | 'https'`를 입력하지 않아도 자동으로 `'http://'`를 추가하여 자동 링크 변환 기능과 preview card를 지원합니다.
* 사용자가 markdown 링크에서 프로토콜을 입력하지 않았을때 '현재 도메인 + 입력한 링크'로 주소가 설정되는 현상을 고쳤습니다.
> fix: 채팅 자동 링크 변환 시 발생하는 문제들 해결
