bear-bear-bear/mogakco

- .eslintrc.js
- emotion Styled 네이밍 컨벤션에 적합하지 않습니다
> feat: export가 하나일땐 export default로 내보내야 하는 eslint 규칙 삭제

- tsconfig.json
next.js에서 root에 tsconfig이 있을시에 tsconfig에 next의 ts 관련 설정을 자동 삽입하던 문제를 수정했습니다.
예외적으로 compilerOptions.jsx 옵션은 디폴트 값이 undefined 인데 해당 값은 json에서 취급하지 않아 미리 입력해둘 수 없었는데,  백엔드 개발에 영향을 미치지 않는 옵션이라 생각하여 next에서 자동으로 설정하는 값인 "preserve"로 냅두었습니다. 해당 옵션으로 문제 발생 시 말씀해주세요
> fix: 프론트 작업 도중 tsconfig이 자동으로 수정되던 문제 수정

- .gitignore
- tsconfig.build.json
- tsconfig.json
- tsconfig.server.json
> 수정: next 의 tsconfig 간섭 해결

- nest/modules/app.module.ts
- nest/test/e2e/auth/user-login.e2e-spec.ts
- nest/test/e2e/helper/support.ts
* /api/auth/login 로그인 테스트
* /api/auth/test 로그인 상태 여부 테스트 ( 테스트에서만 쓰이는 Api )
* /api/auth/refresh-token 새로운 accessToken 발급
* /api/auth/logout 로그아웃 테스트
* * *
> TEST: 백엔드 로그인 테스트 작성

- next/.babelrc
- next/components/landing/Header/style.tsx
- next/next.config.js
- next/tsconfig.json
* 주요 디렉터리에 대한 path alias 를 추가하였습니다.
* path alias 구분은 접두사 (prefix) 를 지정해 주는 것이 좋습니다. ( 일반 경로와 구분 )
* [docs](https://nextjs.org/docs/advanced-features/module-path-aliases) next webpack 설정에서 alias 를 지정해주지 않아도, 알아서 tsconfig.json 을 참고합니다.
> FEATURE: 프런트엔드 Path Alias 수정 및 추가

- next/pages/chat/[id].tsx
* return 객체에 대해서 무조건 { props: { ... } } 형태를 갖추던 지, optional 로 지정된 형태가 지정되어야 타입에러를 발생시키지 않는 듯 합니다.
* 서버 측에서 문제가 생겼을 때 ( 500 ) 유연하게 처리되게 끔 하였습니다.
> FIX: Next SSR 리턴 타입 수정

- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
* mutate 두번 째 인자 false ( shouldRevalidate ) 를 지정해주지 않는다면, Optimism UI 가 작동합니다.
> FIX: Landing Email 폼 반영 되게 끔 수정

- next/components/common/Input/components.tsx
- next/components/common/Input/typings.ts
- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
- next/components/landing/Header/index.tsx
- next/components/sign-in/index.tsx
- next/components/sign-up/Start/index.tsx
- next/lib/isAllPropertyTruthy.ts
- next/pages/sign-in.tsx
로그인 페이지 퍼블리싱 및 API 요청 까지의 단순 기능이 포함된 PR입니다.
[#144](https://github.com/bear-bear-bear/mogakco/issues/144) 에서 설명되는 응답 값에 대한 로직은 아직 구현되지 않았습니다.
인풋 기본 값에 [#144](https://github.com/bear-bear-bear/mogakco/issues/144) 에서 말하는 모각코 기본 이메일 계정을 넣었는데, 해당 계정이 시딩에 구현되있진 않네용 ?
이메일 로그인 파트는 위처럼 되도록 추후 수정 예정입니다. 지금은 뭔가 구려..
> FEAT: 로그인 페이지 퍼블리싱 및 기본 기능

- next/components/landing/ContentBlock/LeftContentBlock/index.tsx
FOCUS 이벤트가 발생하면 해당 엘리먼트를 정중앙으로 위치시키도록 뷰박스가 이동하는데, 랜딩 페이지 진입 시 email ref로 포커스 되는 기존 기능이  모바일 환경에서 작동 시 뷰박스 이동이로 헤더가 안보이고 svg 이미지가 짤려보이는 문제를 발견. 해당 기능을 삭제했습니다.
> FIX: 랜딩 이메일 첫 진입 시 포커스 삭제

- nest/package-lock.json
- nest/package.json
- nest/src/models/chat/chat.gateway.ts
- next/hooks/useSocket.tsx
- next/hooks/useSocketTest.tsx
- next/pages/video-chat/[id].tsx
* 서버, 클라이언트 모두 소켓 라이브러리 버전을 4.2.3 을 맞췄습니다. ( 서버 types 3.x 정상 )
* 클라이언트에서 임시 테스트용 소켓 연결 훅을 작성하고, 채팅방에서 소켓 연결이 성립되는 것을 확인하였습니다.
> feat: Socket.io 4.2.3 으로 Server, Client Socket 연결 작성

- nest/src/authentication/auth.service.ts
- next/components/sign-in/index.tsx
- next/components/sign-up/Optional/index.tsx
- next/hooks/useUser.tsx
- next/lib/apiClient.ts
- next/lib/token.ts
- next/pages/dashboard/index.tsx
- next/pages/sign-in/index.tsx
- next/pages/sign-up/optional.tsx
* 첫 번째로 로그아웃 상태인 지 검사하고 인터셉터 과정을 패스합니다.
* 변경된 로직에 적응치 않고, 본인 정신 정상 상태에서 개발되지 않았으니 검사 부탁드립니다.
* 기존 HttpOnly 를 false 로 해둔 이유가 jwt 값은 키 없이 복호화해볼 수 없기 때문이었습니다.
Closes #295
---
**useUser 훅스에서 발생하던 아래 문제들 수정**
- 컴포넌트의 useUser 가 부모 페이지의 useUser props 값을 덮어버리는 문제
- 리다이렉션이 제대로 수행되지 않는 문제
- 타입 설정이 잘못되어 있던 문제
- 불필요한 조건절이 들어가있던 문제
추가기능 - user가 필요한 페이지에선 리프레쉬 토큰이 쿠키에 존재할때만 요청을 보내도록 설정 (즉, 리프레쉬 토큰이 없을 경우 user가 없는 것으로 가정) - 사용자가 고의적으로, 혹은 인지하지 못한 상태로 쿠키를 지울경우에 대한 리디렉션 로직은 다음 PR에 올리겠습니다.
> feat: 로그아웃 상태일 때 accessToken 갱신 방지

- nest/src/authentication/auth.controller.ts
- next/hooks/useUser.tsx
- next/pages/dashboard/index.tsx
- next/pages/video-chat/[id].tsx
- next/typings/auth.ts
**결국 isLoggedIn 을 사용하기로 했습니다**. 미안합니다. 백측은 복구해뒀습니다.
isLoggedIn을 사용하면 '유저 정보없음' (user.isLoggedIn === false) 상태와 '아직 데이터를 요청하지 않음'(user === undefined)을 구분할 수 있습니다. 하지만 isLoggedIn을 사용하지 않으면 이를 구분할 수 없습니다. 둘 다 undefined 거든요.
둘을 구분할 수 없을때 생기는 문제는 다음과 같습니다.
1. swr은 데이터 패칭 중 조건부 가져오기 또는 종속 가져오기와 함께 사용할 때 요청이 일시 중지된 경우 data를 undefined로 띄웁니다. 이 때 리디렉션 로직을 멈추지 않으면 리디렉션 로직상 무한 루프가 발생하는데, 기존에는 user가 undefined라면 `if (!user) return` 했기때문에 문제가 발생하지 않았지만 isLoggedIn을 삭제하고 user가 있냐, 없냐로만 판단하는 변경 후 로직은 `if (!user) return`를 쓸 수 없습니다.
더 문제가 많은데 머릿속 정리가 안되어 하나만 씁니당 ㅋㅋ.. 굉장히 여러 방면으로 시도해봤는데, 현재 로직상 isLoggedIn 사용은 불가피한듯 합니다.
---
타입을 다음과 같이 변경했습니다.
``` ts
// BEFORE
/**
* 토큰으로 유저 정보를 요청했을 떄의 성공 응답
*/
export interface IUserGetResponse extends IUserInfo {
isLoggedIn: boolean; // true
}
/**
* 토큰으로 유저 정보를 요청했을 떄의 실패 응답 …
```
> fix: useUser 타입문제 수정

- next/components/common/Profile/ProfileModal.tsx
- next/components/common/Profile/index.tsx
- next/components/common/Profile/style.tsx
- next/components/common/ServiceHeader/style.tsx
- next/components/dashboard/Container/style.tsx
- next/components/globalStyles/_Variables.tsx
- next/components/globalStyles/index.tsx
- next/components/my-page/Container/style.tsx
- next/pages/dashboard/index.tsx
- next/pages/my-page/account-setting.tsx
- next/pages/my-page/calendar.tsx
- next/pages/my-page/index.tsx
채팅페이지에는 우측 상단 프로필 컴포넌트만 들어갈 예정입니다.
모달을 dialog element로 만들지 않은 이유는 브라우저 지원도 때문입니다.
> feat: 서비스 헤더를 대시보드 페이지에도 적용하고 그에 맞춰 스타일 보완

- nest/package-lock.json
- nest/package.json
- nest/src/authentication/auth.controller.ts
- nest/src/common/decorators/swagger/auth.decorator.ts
- nest/src/config/database/mariadb.module.ts
- nest/src/mail/assets/user-verify.pug
- nest/src/mail/email.service.ts
- nest/src/models/chat/entities/anonymous-room-user.entity.ts
- nest/src/models/chat/entities/chat-file.entity.ts
- nest/src/models/chat/entities/room.entity.ts
- nest/src/models/chat/repositories/anonymous-room-user.repository.ts
- nest/src/models/chat/repositories/chat-file.repository.ts
- nest/src/models/user/entities/user.entity.ts
* 현재 다른 도메인 통신 간 쿠키 설정이 지원되어 있으나, 테스트 서버에서 정상 동작하지 않기에 수동으로 헤더를 작성해보았습니다.
* 프로덕션에 대해 이메일 코드를 수정하였습니다.
* 익명 사용자에 대한 모델링을 현재 PR에 사전에 작성하였습니다.
* 채팅방 파일을 모델링 해두었으며, 타입 라이브러리를 사전에 작성하였습니다.
* swagger 에서 send-email 에 대해 테스트 하지 못하는 문제를 수정하였습니다.
* 커스텀 헤더 수정에 대한 코드는 테스트 서버에서 정상적으로 동작한다면 리팩터링 하겠습니다.
* 이 후 PR 에서 익명 채팅 또는 채팅 파일 기능을 지원하기 위한 ORM 모델링을 현재 PR 에서 수행했습니다.
* 채팅_파일(chat_files), 채팅_익명_사용자(anonymous_room_users)
* [ERD](https://www.erdcloud.com/d/5C3evcdRWn85gfjc2)
> feat: 모델링 + 프로덕션에 대한 코드 수정

- next/src/components/common/Select/index.tsx
- next/src/components/my-page/AccountSetting/index.tsx
- next/src/components/my-page/AccountSetting/section/Email.tsx
- next/src/components/my-page/AccountSetting/section/JobSelect.tsx
- next/src/components/my-page/AccountSetting/section/SkillsSelect.tsx
- next/src/components/my-page/AccountSetting/section/Username.tsx
- next/src/components/my-page/AccountSetting/style.tsx
- next/src/components/sign-up/Optional/JobSelect.tsx
- next/src/lib/apis.ts
- next/src/lib/regex.ts
- next/src/lib/toSelectOptions.ts
- next/src/pages/api/user/[id].ts
- next/src/pages/api/user/index.ts
- next/src/pages/my-page/account-setting.tsx
- next/typings/auth.ts
user를 삭제합니다. 쿠키를 제거하고 성공응답을 보냅니다. 프런트측에선 성공응답 수신 후 토큰 정보를 삭제하고 user를 isLoggedin false 처리합니다.
user 정보를 덮어씁니다. password를 제외한 유저 정보 (id, username, email, skills, job) 가 req에 담깁니다. 해당 유저 정보를 덮어쓰고, 해당 덮어씌워져 변경된 유저의 정보를 반환합니다.
> feat: 계정 설정 페이지 Next api 임시 구현, 기능과 UI 작업 완료

- nest/src/authentication/auth.controller.ts
- nest/src/authentication/modules/jwt.module.ts
- nest/src/authentication/strategies/jwt-admin.strategy.ts
- nest/src/common/decorators/swagger/auth.decorator.ts
- nest/src/common/guards/admin.guard.ts
- nest/src/common/guards/non-auth.guard.ts
- nest/src/database/seeders/a3-test-admin-user.ts
- nest/src/models/user/entities/user-roles.entity.ts
* 테스트를 Swagger 로 만들었습니다. ( 어드민 권한 Api 가 현재 없어서 Swagger 로 작성함 )
> 테스트에 사용하고, 서비스에 사용하지 않을 Api 라 Swagger Response 가 없습니다.
> 현재 테스트 Api 는 추 후, 테스트 구간으로 따로 관리하도록 하겠습니다.
* 이제 어드민 기능이 생겼습니다. ( 기존 유저 테이블에서 생성 )
* 어드민만 권한을 허용하는 전략과 가드 시스템을 작성하였습니다.
계정 admin@admin.com
비밀번호 admin
`npm run seed:run`
> feat: 어드민 및 어드민 전용 인증 구현

- nest/src/common/decorators/swagger/chat.decorator.ts
- nest/src/database/seeders/a4-test-anonymous-props.ts
- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/dto/anonymous-prop.dto.ts
- nest/src/models/chat/entities/anonymous_names.entity.ts
- nest/src/models/chat/entities/anonymous_prefix.entity.ts
- nest/src/models/chat/interface/controller.ts
- nest/src/models/chat/interface/service.ts
- nest/src/models/chat/repositories/anonymous-room-user.repository.ts
- nest/src/models/user/entities/user.entity.ts
- nest/test/e2e/helper/enum.ts
- next/src/hooks/useSocket.tsx
* 채팅방 익명 사용자에 대한 데이터를 이제 DB 모델에서 랜덤으로 가져오는 방식으로 변경하였습니다.
* 어드민의 권한으로 익명 사용자 이름 정보에 대한 데이터를 추가할 수 있습니다.
* 채팅 업로드에 대한 인터페이스 초안이 작성되어 있습니다.
> feat: 익명 사용자에 대한 기능과 Api 추가

- nest/src/common/decorators/swagger/chat.decorator.ts
- nest/src/models/chat/chat.controller.ts
- nest/src/models/chat/chat.gateway.ts
- nest/src/models/chat/chat.service.ts
- nest/src/models/chat/interface/controller.ts
- nest/src/models/chat/interface/service.ts
* 구현 Api 에 자세한 정보는 Swagger 확인해주세요.
* 익명 접두어에 관한 업데이트, 삭제, 전체 불러오기 추가
* 익명 이름에 대한 업데이트, 삭제, 전체 불러오기 추가
* 구현 된 모든 Api 는 관리자 권한 접근을 필요로 합니다.
* 총 8개의 api 항목
> feat: 익명에 관한 Api 목록 작성

- next/src/components/video-chat/ChatSection/ChatList/index.tsx
채팅 추가 시 기본적으론 스크롤 뷰를 제일 아래로 (방금 추가된 채팅으로) 이동하되, 채팅 상단부를 되돌아보려고 일부러 위로 스크롤한 경우엔 채팅이 추가되어도 스크롤 맨 아래로 뷰가 이동하지 않도록 설정했습니다.
> feat: 채팅 추가 시 스크롤 bottom으로 가도록 추가

- next/src/pages/index.tsx
서비스 페이지에 있다가 user 정보가 없어져 랜딩으로 리디렉션 될 경우 발생하는 flash 제거.  (예를 들면, 사용자가 서비스 페이지에 있다가 탭을 나갔다 와서 user정보가 말소되어, 랜딩 페이지로 리디렉션 되고 useUser 요청을 다시 보내서 응답이 올 때까지의 공백동안 발생하는 flash. 프런트 개발 도중 핫리로딩 시 발생하니 자주 보셨을겁니다)
랜딩페이지 첫 로딩은 느려보이겠지만, flash 보단 낫다고 판단했습니다.
> fix: 서비스 페이지에서 useUser 요청 도중 user가 undefined일때 나타나는 랜딩페이지 flash fix

- next/package-lock.json
- next/package.json
- next/src/components/video-chat/ChatSection/Chat/Message.tsx
링크 자동 변환은 왜 에디터에 기능 있을거라곤 생각을 못했지; 어제 삽질했네요
---
* 링크 자동 변환 기능 추가
* http/ https 혹은 'www'로 시작해야 링크 자동 변환이 지원됩니다.
* naver.com (x) 
* www.naver.com (o)
* http://naver.com (o)
* http://www.naver.com (o)
* 링크 preview 기능 추가
* http/ https 가 붙어있어야 preview가 동작하게 했습니다. (슬랙 참고함)
* naver.com (x) 
* www.naver.com (x)
* http://naver.com (o)
* https://www.naver.com (o)
* 한 텍스트 내의 중복 링크는 개중 하나만 띄웁니다.
* `'이것은 네이버 링크들 > http://naver.com https://naver.com https://www.naver.com'`  => 셋 중 하나만 띄웁니다. markdown 문법으로 링크를 `[https://naver.com](https://naver.com)` 이렇게 써도 중복 제거해준단 소리
* 설치된 라이브러리
* linkify: 주어진 plain 텍스트에서 링크 패턴을 모두 찾아줌
* @dhaiwat10/react-link-preview: 리액트 링크 preview 라이브러리. 스켈레톤 로딩 지원
> feat: 입력한 채팅에 대한 링크 자동변환과 preview 기능 추가
